
baseURL = "https://hrmnjt.dev"

languageCode = "en-us"
theme = "researcher"

title = "hrmnjt::sttp://"

disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable  KaTeX (https://katex.org/) globally

[params]
  author = "Harmanjeet Singh Nagi"
  description = "Secure Thought Transfer Protocol by Harmanjeet Singh Nagi"
#   favicon = "favicon.ico"  # path to a .ico to use as favicon
#   logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = "Secure Thoughts Transfer Protocol by hrmnjt"
    url = "https://github.com/hrmnjt/"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    pageWidth = "800px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "whoami"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "posts"
    url = "/posts"
    weight = 2

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
