
languageCode = "en-us"
theme = "cactus"

baseURL = "https://www.hrmnjt.dev"
title = "sttp://secure-thought-transfer-protocol"
copyright = "Harmanjeet Singh Nagi"

# disqusShortname = "example"
# googleAnalytics = "UA-1234-5"

# summaryLength = 2

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    style = "native"

[params]
  dateFormat = "2006-01-02"
  colortheme = "dark" # dark, light, white, or classic
  rss = true

  # Home page settings
  description = """Welcome to securely transfered thoughts brought to you by 
  Harman!
  
  I'm a technology enthusiast who works @MajidAlFuttaim on system 
  programming, analytical and transactional databases, editing yaml  
  and dataops.
  """
  mainSection = "posts"
  showAllPostsOnHomePage = false
  postsOnHomePage = 3
  tagsOverview = false
  showProjectsList = true
  projectsUrl = "https://github.com/hrmnjt"
  
  # Post page settings
  show_updated = false # default

  [[params.social]]
    name = "github"
    link = "https://github.com/hrmnjt"
  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/hrmnjts"
  [[params.social]]
    name = "linkedin"
    link = "https://linkedin.com/in/hrmnjt"
  [[params.social]]
    name = "email"
    link = "hrmnjt@hrmn.in"

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  googleAnalyticsAsync = false # use asynchronous tracking. Synchronous tracking by default
