
# name of the workflow
# one can create multiple workflows and each one can be triggered differently
# to perform different actions
name: Blog Update

# condition on which this workflow will trigger
# you can specify events or can add a schedule for regularized builds
on:
  push:
    branches: [ main ] # denotes that "on push on main branch workflow will trigger"

jobs:
  build:
    runs-on: ubuntu-18.04 # base os on which the setup would be executed

    steps:
      - name: Checkout # checkout step to checkout the repository in above environment
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo # setup step to install hugo on the system for build step
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build # build step to create static content using hugo binary
        run: hugo --minify

      - name: Deploy # deploy step to deploy the latest code on the gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # secret token added for deploy step
          publish_dir: ./public # publishing directory for hugo
          cname: www.hrmnjt.dev # custom domain name
          commit_message: ${{ github.event.head_commit.message }}
